In [71]:
import numpy as np
# np.set_printoptions(legacy='1.25')

In [72]:
# Vector ops : vectors denoted as columns in Lin Alg, as a row in numpy
u = np.array([2,4,5,6])
u
v = np.array([1,0,0,2])
v

array([1, 0, 0, 2])

In [73]:
u + v

array([3, 4, 5, 8])

In [74]:
u.shape

(4,)

In [75]:
u.shape[0]

4

In [76]:
# vector by vector multiplication is called the dot product and produces a single number
# each element is multiplied, element-wise, then summed
# get the transpose of one of the vectors so that one is a row, one is a column, then do dot product
# example of the numpy dot product, built-in func is u.dot(v)
def vec_vec_mult(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]
    result = 0.0
    for i in range(n):
        result = result + u[i] * v[i]

    return result

In [77]:
vec_vec_mult(u, v)

14.0

In [78]:
u.dot(v)

14

In [79]:
t = np.array([[2,4,5,6],[1,2,1,2],[3,1,2,1]])
t

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [80]:
# for matrix by vector dot product, each row of matrix gets dot'ed by the vector
t.dot(v)

array([14,  5,  5])

In [81]:
# example where the dimensions don't match to show error
vv = np.ones(3)
vv

array([1., 1., 1.])

In [82]:
t.dot(vv) # expect error

ValueError: shapes (3,4) and (3,) not aligned: 4 (dim 1) != 3 (dim 0)

In [83]:
# matrix dot matrix
w = np.array([[1,1,2],[0,.5,1],[0,2,1],[2,1,0]])
w

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [84]:
w.shape[0] # row shape

4

In [85]:
w.shape[1] # column shape

3

In [86]:
x = t.dot(w)
x

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [87]:
# Identity Matrix: square matrix with 1's on the diagonal and 0's everywhere else.
# when I matrix is doted with itself it returns itself
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [88]:
I.dot(I)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [89]:
w.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [90]:
# Matrix Inverse. Requires a square matrix (like x and I are, above)
x_inv = np.linalg.inv(x)
x_inv

array([[-0.1503268 ,  0.90849673, -0.2875817 ],
       [ 0.26143791, -0.79738562,  0.06535948],
       [-0.16339869,  0.24836601,  0.20915033]])

In [91]:
# dot of a square matrix with its inverse yields the Identity matrix
x.dot(x_inv)

array([[ 1.00000000e+00, -2.27595720e-15, -3.88578059e-16],
       [ 8.32667268e-17,  1.00000000e+00,  5.55111512e-17],
       [ 8.32667268e-17, -2.77555756e-16,  1.00000000e+00]])

In [92]:
x_inv.dot(x)

array([[ 1.00000000e+00,  8.32667268e-16,  7.77156117e-16],
       [-1.11022302e-15,  1.00000000e+00, -1.11022302e-15],
       [ 9.43689571e-16,  8.04911693e-16,  1.00000000e+00]])