In [141]:
import pandas as pd

In [142]:
df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv")


In [143]:
"Q1: Pandas Version: " + pd.__version__

'Q1: Pandas Version: 2.2.3'

In [144]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2160 entries, 0 to 2159
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Laptop        2160 non-null   object 
 1   Status        2160 non-null   object 
 2   Brand         2160 non-null   object 
 3   Model         2160 non-null   object 
 4   CPU           2160 non-null   object 
 5   RAM           2160 non-null   int64  
 6   Storage       2160 non-null   int64  
 7   Storage type  2118 non-null   object 
 8   GPU           789 non-null    object 
 9   Screen        2156 non-null   float64
 10  Touch         2160 non-null   object 
 11  Final Price   2160 non-null   float64
dtypes: float64(2), int64(2), object(8)
memory usage: 202.6+ KB


In [145]:
"Q2: Records Count: " + str(df.shape[0])

'Q2: Records Count: 2160'

In [146]:
df.head(2)

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   

        Model            CPU  RAM  Storage Storage type  GPU  Screen Touch  \
0  ExpertBook  Intel Core i5    8      512          SSD  NaN    15.6    No   
1          Go  Intel Celeron    8      256          SSD  NaN    15.6    No   

   Final Price  
0       1009.0  
1        299.0

In [147]:
brands = df.Brand.unique()
"Q3: Unique Brands: " + str(len(brands))

'Q3: Unique Brands: 27'

In [148]:
nullColumns = df.isnull().sum().values > 0
"Q4: Column count with missing values: " + str(len(list(filter(lambda x: x, nullColumns))))

'Q4: Column count with missing values: 3'

In [149]:
# check to make sure capitalization doesn't matter
df.Brand.unique()

array(['Asus', 'Alurin', 'MSI', 'HP', 'Lenovo', 'Medion', 'Acer', 'Apple',
       'Razer', 'Gigabyte', 'Dell', 'LG', 'Samsung', 'PcCom', 'Microsoft',
       'Primux', 'Prixton', 'Dynabook Toshiba', 'Thomson', 'Denver',
       'Deep Gaming', 'Vant', 'Innjoo', 'Jetwing', 'Millenium', 'Realme',
       'Toshiba'], dtype=object)

In [150]:
maxDellPrice = df[df.Brand == "Dell"]["Final Price"].max()
"Q5: Max Dell Price: " + str(maxDellPrice)

'Q5: Max Dell Price: 3936.0'

In [151]:
"Screen mean before update = " + str(df.Screen.mean().round(4))

'Screen mean before update = 15.1681'

In [152]:
medianScreenValue = df.Screen.median()
medianScreenValue

np.float64(15.6)

In [153]:
modeScreenValue = df.Screen.mode()
modeScreenValue

0    15.6
Name: Screen, dtype: float64

In [154]:
# Before table modification the mode and median are the same value, 15.6
df.Screen = df.Screen.fillna(15.6)

In [155]:
newMediunScreen = df.Screen.median()
newMediunScreen

np.float64(15.6)

In [156]:
df.Screen.isnull().sum()

np.int64(0)

In [157]:
"Screen mean after update = " + str(df.Screen.mean().round(4))

'Screen mean after update = 15.1689'

In [158]:
# Q6: Has it changed? Answer: No.
# However, for sanity check, we note the mean has changed"

In [159]:
injoo = df[df.Brand == "Innjoo"]

In [160]:
X = injoo[["RAM", "Storage", "Screen"]].values

In [161]:
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [162]:
XT = X.T // transpose rows / columns
XT

SyntaxError: invalid syntax (4267944022.py, line 1)

In [163]:
XTX = XT.dot(X)
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [164]:
import numpy as np

In [165]:
XTX_i = np.linalg.inv(XTX)
XTX_i


array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [166]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])

In [167]:
w = XTX_i.dot(XT).dot(y)
w

array([45.58076606,  0.42783519, 45.29127938])

In [168]:
#Q7 answer
"Q7: Linear regression result: " + str(np.sum(w).round(2))

'Q7: Linear regression result: 91.3'