In [4]:
import numpy as np

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [7]:
np.full(10, 2.51)

array([2.51, 2.51, 2.51, 2.51, 2.51, 2.51, 2.51, 2.51, 2.51, 2.51])

In [8]:
a = np.array([1,2,3,4,5,9,12])

In [9]:
a[3]

np.int64(4)

In [10]:
a[3] = 50

In [11]:
a

array([ 1,  2,  3, 50,  5,  9, 12])

In [12]:
a[3]

np.int64(50)

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(3,9)

array([3, 4, 5, 6, 7, 8])

In [16]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [17]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])

In [22]:
n[1,1] = 20
n

array([[ 1,  2,  3],
       [ 4, 20,  6],
       [ 7,  8,  9]])

In [25]:
# get column 0
n[:,0]

array([1, 4, 7])

In [27]:
# assign 0 to column 2
n[:, 2] = [0, 0, 0]
n

array([[ 1,  2,  0],
       [ 4, 20,  0],
       [ 7,  8,  0]])

In [35]:
# np.random.seed(<some value>) to keep same values
random = np.random.rand(5, 2)
random

array([[0.39669732, 0.60874878],
       [0.06959567, 0.50270285],
       [0.22214125, 0.7524605 ],
       [0.27982073, 0.4381561 ],
       [0.73987475, 0.14077371]])

In [36]:
random *=2
random

array([[0.79339464, 1.21749757],
       [0.13919133, 1.00540571],
       [0.44428251, 1.50492099],
       [0.55964147, 0.87631219],
       [1.47974951, 0.28154743]])

In [38]:
np.random.randint(low=0, high=100, size=(3,3))

array([[15, 83, 57],
       [22, 94, 25],
       [99, 53, 41]])

In [39]:
# element-wise ops
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [41]:
b = a + 1
b

array([1, 2, 3, 4, 5])

In [42]:
10 + (a * 2)

array([10, 12, 14, 16, 18])

In [47]:
c = (10 + (a * 2)) ** 2
c

array([100, 144, 196, 256, 324])

In [49]:
a + b

array([1, 3, 5, 7, 9])

In [51]:
d = a + b - c/50
d

array([-1.  ,  0.12,  1.08,  1.88,  2.52])

In [52]:
# comparison element-wise
d > 0

array([False,  True,  True,  True,  True])

In [54]:
d < a

array([ True,  True,  True,  True,  True])

In [55]:
# summarizing ops
d.max()

np.float64(2.5199999999999996)

In [56]:
d.mean()

np.float64(0.9199999999999999)

In [57]:
d.std()

np.float64(1.2516868617989083)